version: '3'

services:
    netspaces-web:
        build:
            context: ./
            target: netspaces-web
        ports:
            - 3000:3000
        volumes:
            - .:/app
        depends_on:
            - netspaces-api

    netspaces-api:
        build:
            context: ./
            target: netspaces-api
        environment:
            - PORT=3333
        ports:
            - 3333:3333
        volumes:
            - .:/app
        depends_on:
            - netspaces-eventstore
            - netspaces-mongodb
            - mongo-express

    netspaces-eventstore:
        container_name: netspaces-eventstore
        image: eventstore/eventstore:20.10.2-buster-slim
        environment:
            - EVENTSTORE_CLUSTER_SIZE=1
            - EVENTSTORE_RUN_PROJECTIONS=All
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_EXT_TCP_PORT=1113
            - EVENTSTORE_EXT_HTTP_PORT=2113
            - EVENTSTORE_INSECURE=true
            - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
            - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
        ports:
            - '1113:1113'
            - '2113:2113'
        volumes:
            - type: volume
              source: eventstore-volume-data
              target: /var/lib/eventstore
            - type: volume
              source: eventstore-volume-logs
              target: /var/log/eventstore

    netspaces-mongodb:
        container_name: netspaces-mongodb
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - type: volume
              source: mongo-volume-data
              target: /data/db

    mongo-express:
        container_name: netspaces-mongoexpress
        depends_on:
            - netspaces-mongodb
        image: mongo-express:latest
        ports:
            - 8081:8081

volumes:
    eventstore-volume-data:
    eventstore-volume-logs:
    mongo-volume-data:
    mongoclient-volume-data:
