version: '3'

services:
    netspaces-web:
        build:
            context: ./
            target: netspaces-web
        ports:
            - 3000:3000
        volumes:
            - .:/app
        depends_on:
            - netspaces-api
        networks:
            - netspaces-network

    netspaces-api:
        build:
            context: ./
            target: netspaces-api
        environment:
            - PORT=3333
            - REDIS_HOST="netspaces-cache"
            - REDIS_PORT=6379
        ports:
            - 3333:3333
        volumes:
            - .:/app
        depends_on:
            - netspaces-eventstore
            - netspaces-mongodb
            - mongo-express
            - netspaces-cache
        networks:
            - netspaces-network

    netspaces-booking-microservice:
        build:
            context: ./
            target: netspaces-booking-microservice
        ports:
            - 3334:3334
        volumes:
            - .:/app
        networks:
            - netspaces-network
        depends_on:
            - kafka

    netspaces-eventstore:
        container_name: netspaces-eventstore
        image: eventstore/eventstore:20.10.2-buster-slim
        environment:
            - EVENTSTORE_CLUSTER_SIZE=1
            - EVENTSTORE_RUN_PROJECTIONS=All
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_EXT_TCP_PORT=1113
            - EVENTSTORE_EXT_HTTP_PORT=2113
            - EVENTSTORE_INSECURE=true
            - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
            - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
        ports:
            - '1113:1113'
            - '2113:2113'
        volumes:
            - type: volume
              source: eventstore-volume-data
              target: /var/lib/eventstore
            - type: volume
              source: eventstore-volume-logs
              target: /var/log/eventstore
        networks:
            - netspaces-network

    netspaces-mongodb:
        container_name: netspaces-mongodb
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - type: volume
              source: mongo-volume-data
              target: /data/db
        networks:
            - netspaces-network

    mongo-express:
        container_name: mongo-express
        depends_on:
            - netspaces-mongodb
        image: mongo-express:latest
        ports:
            - 8081:8081
        networks:
            - netspaces-network

    netspaces-cache:
        container_name: netspaces-cache
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - cache:/data
        networks:
            - netspaces-network

    zookeeper:
        container_name: zookeeper
        image: wurstmeister/zookeeper
        networks:
            - netspaces-network
        ports:
            - 2181:2181
        environment:
            - ZOOKEEPER_CLIENT_PORT=2181
            - ZOOKEEPER_TICK_TIME=2000
            - ALLOW_ANONYMOUS_LOGIN=yes
        restart: unless-stopped

    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        links:
            - zookeeper
        networks:
            - netspaces-network
        ports:
            - 9092:9092
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_ADVERTISED_HOST_NAME=kafka
            - KAFKA_DELETE_TOPIC_ENABLE=false
            - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - KAFKA_ADVERTISED_PORT=9092
        depends_on:
            - zookeeper
        restart: unless-stopped

volumes:
    eventstore-volume-data:
    eventstore-volume-logs:
    mongo-volume-data:
    mongoclient-volume-data:
    cache:
        driver: local

networks:
    netspaces-network:
        driver: bridge
