version: '3'

services:
    netspaces-web:
        build:
            context: ./
            target: netspaces-web
        ports:
            - 3000:3000
        volumes:
            - .:/app
        depends_on:
            - netspaces-api
        networks:
            - netspaces-network

    netspaces-api:
        build:
            context: ./
            target: netspaces-api
        environment:
            - PORT=3333
            - REDIS_HOST="netspaces-cache"
            - REDIS_PORT=6379
        ports:
            - 3333:3333
        volumes:
            - .:/app
        depends_on:
            - netspaces-eventstore
            - netspaces-mongodb
            - mongo-express
            - netspaces-cache
        networks:
            - netspaces-network

    netspaces-booking-microservice:
        build:
            context: ./
            target: netspaces-booking-microservice
        environment:
            - PORT=3333
        ports:
            - 3334:3333
        volumes:
            - .:/app
        networks:
            - netspaces-network
        depends_on:
            - kafka
            - netspaces-booking-microservice-eventstore
            - netspaces-booking-microservice-mongodb

    netspaces-gateway:
        build:
            context: ./
            target: netspaces-gateway
        ports:
            - 3335:3335
        volumes:
            - .:/app
        networks:
            - netspaces-network
        depends_on:
            - kafka

    netspaces-eventstore:
        image: eventstore/eventstore:20.10.2-buster-slim
        environment:
            - EVENTSTORE_CLUSTER_SIZE=1
            - EVENTSTORE_RUN_PROJECTIONS=All
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_EXT_TCP_PORT=1113
            - EVENTSTORE_EXT_HTTP_PORT=2113
            - EVENTSTORE_INSECURE=true
            - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
            - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
        volumes:
            - type: volume
              source: eventstore-volume-data
              target: /var/lib/eventstore
            - type: volume
              source: eventstore-volume-logs
              target: /var/log/eventstore
        networks:
            - netspaces-network

    netspaces-booking-microservice-eventstore:
        image: eventstore/eventstore:20.10.2-buster-slim
        environment:
            - EVENTSTORE_CLUSTER_SIZE=1
            - EVENTSTORE_RUN_PROJECTIONS=All
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_EXT_TCP_PORT=1113
            - EVENTSTORE_EXT_HTTP_PORT=2113
            - EVENTSTORE_INSECURE=true
            - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
            - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
        volumes:
            - type: volume
              source: booking-microservice-eventstore-volume-data
              target: /var/lib/eventstore
            - type: volume
              source: booking-microservice-eventstore-volume-logs
              target: /var/log/eventstore
        networks:
            - netspaces-network

    netspaces-mongodb:
        image: mongo:latest
        volumes:
            - type: volume
              source: mongo-volume-data
              target: /data/db
        networks:
            - netspaces-network

    netspaces-booking-microservice-mongodb:
        image: mongo:latest
        volumes:
            - type: volume
              source: mongo-booking-microservice-volume-data
              target: /data/db
        networks:
            - netspaces-network

    mongo-express:
        depends_on:
            - netspaces-mongodb
        image: mongo-express:latest
        ports:
            - 8081:8081
        networks:
            - netspaces-network

    netspaces-cache:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - cache:/data
        networks:
            - netspaces-network

    kafka:
        image: docker.io/bitnami/kafka:3.4
        ports:
            - '9092:9092'
        volumes:
            - 'kafka-volume-data:/bitnami'
        environment:
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
            - ALLOW_PLAINTEXT_LISTENER=yes
        networks:
            - netspaces-network

volumes:
    eventstore-volume-data:
    eventstore-volume-logs:
    booking-microservice-eventstore-volume-data:
    booking-microservice-eventstore-volume-logs:
    mongo-volume-data:
    mongoclient-volume-data:
    mongo-booking-microservice-volume-data:
    kafka-volume-data:
    cache:
        driver: local

networks:
    netspaces-network:
        driver: bridge
